### ISSUE TITLE
crashes with SDR# 1911 and above

### ISSUE THREAD

**Issue by MELERIX** [rtlsdrblog/rtl-sdr-blog#18]
now with the latest versions of SDR# such as 1911, 1912, and 1913 it crashes after changing frequencies or moving the spectrum a bit, or after few minutes of usage, or also It crashes when you adjust the RF gain, and the bug seems to be in this library.

here are reports about this:
https://groups.io/g/airspy/topic/sdr_1913/99412741
https://forums.radioreference.com/threads/sdr-1911-rtl-sdr.458938/
https://www.reddit.com/r/RTLSDR/comments/14730fj/sdrsharp_rev_1913_bug/
https://www.reddit.com/r/sdr/comments/148ooxb/sdrsharp_last_version_crashes_on_windows/

**Comment by rtlsdrblog** [comment]
Seems to be mostly a problem with some unknown change in SDR# interacting badly with libusb. 

Oddly the standard osmocom, keenerd, and librtlsdr builds all seem to crash immediately on tune, whereas this rtl-sdr-blog branch crashes a bit more rarely. I'm not sure what i'm doing differently to them, but it seems to just be in the way it's built.

I found one workaround that should work for most people:

1) Install the "libusb-win32" driver with Zadig. This is instead of WinUSB or libusbk, both of which appear to have this bug.
2) Also use the rtl-sdr-blog branch x86 .dll in SDR#.

When you combine these two it almost never crashes now. However, after about 5-10 minutes of continuous rapid tuning it might still crash, so this could still be problematic for people using scanner plugins.

**Comment by rtlsdrblog** [comment]
Upon further investigation the libusb-win32 fix may not be possible for everyone. On some machines this driver does not work, and causes SDR# to crash on play. On others it fixes the problem completely.

So I still don't have a universal fix.

**Comment by rtlsdrblog** [comment]
The older SDR# versions are stable too with Keener, and the osmo or rtl-sdr-blog drivers. The osmo drivers do tend to crash when closing SDR# on some machines though. Not sure if the rtl-sdr-blog ones do the same.
