### ISSUE TITLE
rtl_test shows no errors

### ISSUE THREAD

**Issue by bc4040** [rtlsdrblog/rtl-sdr-blog#43]
Generic RTL2832U OEM tuner was in a state where it was unresponsive (rtl_sdr output produced a 0 byte file in all cases), yet rtl_test does not report any errors in this condition.  I believe this may be due to overheating

**Comment by rtlsdrblog** [comment]
An RTL-SDR won't just produce a 0 byte file because of overheating. Overheating can cause the PLL to lose lock, but only at the upper frequencies above 1.5 GHz, and this is very unlikely on a V3 or V4 because of some mods we've done to the hardware. If the PLL loses lock, you'd just get noise as the output file data.
