### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by makew0rld** [rtlsdrblog/rtl-sdr-blog#6]
Is this still the recommended solution for V3 units, or is the original driver software good now?

**Comment by martin-zs** [comment]
I just read through the source code for both rtlsdrblog/rtl-sdr-blog and osmocom/rtl-sdr and I would say use this source for the V3, it has some extra features.

But in reality you can use either.

bias-T support was added to the osmocom/rtl-sdr library as well as the rtl_biast command. 

The gr-osmosdr source block added the "bias=0" or "bias=1" and direct_samp=[0|1|2] argument for rtl devices, which work in a default install of gnuradio since osmocom/gr-osmosdr supported those keywords in June 2017.

**Comment by rtlsdrblog** [comment]
Both solutions are fine. This fork just adds more control over the features for the V3/V4.
